[http]
listen_port = 8081

[https]
listen_port = 8443

# 下面配置多个 tcp 透明代理
# 配置 1：将本地 8082 端口的数据转发到云端的 22 端口
[[tcp]]
listen_port = 8082
remote_addr = "iot-broker.xeewo.com:8883"
#
## 配置 1：将本地 8082 端口的数据转发到云端的 22 端口
#[[tcp]]
#listen_port = 8083
#remote_addr = "192.168.31.197:80"

[target_connection]
dns_cache_ttl = "600s"
connect_timeout = "2s"

